version: '3'

services:
  experiences:
    build: ./
    depends_on:
      - 'database'
    ports:
      - '3636:3636'
    expose:
      - '3636'
  seed:
    build: ./database
    depends_on:
      - database
  database:
    image: mongo
    expose:
      - '27017'
