version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
      - image: circleci/mongo:4.2.7
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx webpack
            - run: npm run lint
  start:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run circleStart
  test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run seed
            - run: npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - start:
          requires:
            - build
      - test:
          requires:
            - build


