version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
      - image: circleci/mongo:4.2.7
    steps:
      - checkout
      - run:
        name: Wait for server to start
        command: dockerize --wait tcp://127.0.0.1:27017 -timeout 180s
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx webpack
            - run: npm run lint
  start:
    docker:
        - image: circleci/node:dubnium
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run circleStart
  test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run:
          name: Wait for server to start
          command: dockerize --wait http://127.0.0.1:3636 -timeout 120s
      - node/with-cache:
          steps:
            - run: npm run seed
            - run: npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - start:
          requires:
            - build
      - test:
          requires:
            - build


