version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:dubnium
      - image: circleci/mongo:4.2.7
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx webpack
            - run: npm run lint
            - run: npm run circleStart
            - run: npm run seed
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
